# Generated by Django 6.0.6 on 2026-07-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosettings',
            name='day_end_hour',
            field=models.PositiveSmallIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='pomodorosettings',
            name='day_start_hour',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
